[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'cairo', 'pango', 'libpng', 'jpeg', 'giflib', 'librsvg', 'pkg-config', 'build-essential', 'fontconfig']

[phases.build]
cmds = ['npm install --build-from-source=canvas', 'fc-cache -fv']

[start]
cmd = 'npm start'
